name: intellispendiq
description: AI-powered personal finance tracker capturing transactions from
  SMS alerts and voice. Offline-first, encrypted, Android-first.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  app_links: ^6.4.1
  bloc: ^9.0.1
  cloud_firestore: ^5.6.12
  connectivity_plus: ^6.1.5
  crypto: ^3.0.6
  drift: ^2.34.0
  equatable: ^2.0.7
  file_picker: ^11.0.2
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  http: ^1.4.0
  hugeicons: ^1.1.7
  image_picker: ^1.2.3
  intl: ^0.20.2
  local_auth: ^3.0.1
  path: ^1.9.0
  path_provider: ^2.1.5
  share_plus: ^12.0.2
  speech_to_text: ^7.4.0
  sqlite3: ^3.5.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  google_sign_in: ^7.2.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.15.0
  drift_dev: ^2.34.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

hooks:
  user_defines:
    sqlite3:
      source: sqlcipher
